### PR TITLE
fix: validation of phone number

### LINKED ISSUE #424: Validation for phone number has to be corrected.
**Actual Behavior**

The input field for the phone number is not validated correctly.

**Expected Behavior**

Letters are validated as false.

**Steps to Reproduce the Bug**

1. Sign in 
2. Click on 'User Management'
3. Click on 'Add User' to create a new user
4. Fill in a phone number with letters

**Environment Details**

- Desktop: \*

  - OS: Windows
  - Browser Google Chrome, Version 86.0.4240.75

pwa_bug_phone_validation

**Additional Context, like Screenshots, Log File Snippets etc.**

[AB#64609](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64609)

### PR DESCRIPTION
**Pull request by cbratsch**
## PR Type

[x] Feature

## What Is the Current Behavior?
input field for for phone number is standard input type text without validation (see issue below for more details)

Issue Number: Closes #424 

## What Is the New Behavior?
- Formly field for phone numbers is available
- Phone number is validated
- most common validation messages (phone and required) are added to the field
- Input for phone number use type "tel" to improve mobile behavior 

## Does this PR Introduce a Breaking Change?

[x] No

## Other Information

[AB#64695](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64695)

### CODE REVIEW

**Comment by shauke** [comment]
Shouldn't there be some sort of validation error message?
image

**Comment by shauke** [comment]
Something seems wrong with the regular expression. The following errors are logged to the browser console when entering numbers in the phone input.
image

File: src/app/shared/formly/types/phone-field/phone-field.component.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+import { FormControl } from '@angular/forms';
+import { FieldType } from '@ngx-formly/core';
+
+@Component({
+  selector: 'ish-phone-field',
+  templateUrl: './phone-field.component.html',
+  changeDetection: ChangeDetectionStrategy.OnPush,
+})
+export class PhoneFieldComponent extends FieldType {
+  pattern: RegExp = /^(?:\+|00)[1-9]\d{0,2}(?: |\-)|((?: |-)[0-9]{3}(?: |-)[0-9]{4})|([0-9]{7,14})$/;
```
Comment (shauke) [inline src/app/shared/formly/types/phone-field/phone-field.component.ts:11]: Something is wrong with this RegEx (see comment browser error.).

**Review by shauke — CHANGES_REQUESTED** [review]
The code looks good to me but there is an additional IAD comment.

File: src/app/shared/formly/types/phone-field/phone-field.component.spec.ts [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+      form: new FormGroup({}),
+    };
+    fixture = TestBed.createComponent(FormlyTestingContainerComponent);
+    component = fixture.componentInstance;
+    element = fixture.nativeElement;
+
+    component.testComponentInputs = testComponentInputs;
+  });
+
+  it('should be created', () => {
```
Comment (SGrueber) [inline src/app/shared/formly/types/phone-field/phone-field.component.spec.ts:46]: add a test if the input field is rendered like in the other formly fields

File: src/app/shared/formly/types/phone-field/phone-field.component.ts (hunk 1 above)
Comment (SGrueber) [reply src/app/shared/formly/types/phone-field/phone-field.component.ts:11]: i think, it would be better to use a special phone number validator instead using the pattern here, because the field is marked red in case of an error but there is no error message.
You could add a new validator in the SpecialValidators class and assign it per default as it is in the email-field.component

**Review by SGrueber — CHANGES_REQUESTED** [review]
Add a documentation to the formly.md file

File: src/app/shared/formly/types/phone-field/phone-field.component.ts [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+  formControl: FormControl;
+
+  prePopulate(field: FormlyFieldConfig) {
+    field.validators = field.validators ?? {};
+    field.validators.validation = [...(field.validators.validation ?? []), SpecialValidators.phone];
+
+    field.validation = field.validation ?? {};
+    field.validation.messages = {
+      ...field.validation?.messages,
+      phone: 'helpdesk.contactus.phone.error',
```
Comment (SGrueber) [inline src/app/shared/formly/types/phone-field/phone-field.component.ts:22]: this localization key should be more general, pls ask IAD for the content

**Review by SGrueber — CHANGES_REQUESTED** [review]

**Comment by SGrueber** [comment]
docu of the phonefield is missing in formly.md

**Review by M-Behr — DISMISSED** [review]
It works very well. Even the number pad opens on my mobile phone. Nice!

**Review by SGrueber — DISMISSED** [review]

**Review by SGrueber — APPROVED** [review]

**Review by iwiederhold — APPROVED** [review]

**Review by M-Behr — APPROVED** [review]

**Review by SGrueber — APPROVED** [review]
