### PR TITLE
SSL certificate error message

### LINKED ISSUE #756: Provide better message when ICM uses self-signed SSL cert
**Actual Behavior**

When ICM backend is not protected with a valid SSL certificate the SSR rendering process logs a not very helpful message into std-out.
`ERROR Http failure response for https://somehost.intershop.de/INTERSHOP/rest/WFS/XYZ-Site/-;loc=en_US;cur=USD/configurations: 0 Unknown Error`

**Expected Behavior**

Please log some information into SSR std-out that SSL trust cannot be established.

**Steps to Reproduce the Bug**

1. Select some ICM_BASE_URL value that fits the SSL certificate requirements
2. Deploy and start containers with `docker-compose up`
3. Open browser to see homepage
4. See error in error log of docker-compose process

[AB#64626](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64626)

### PR DESCRIPTION
**Pull request by Eisie96**
## PR Type

[x] Bugfix

## What Is the Current Behavior?

When ICM backend is not protected with a valid SSL certificate the SSR rendering process logs a not very helpful message into std-out.

Issue Number: Closes #756

## What Is the New Behavior?

Log some information into SSR std-out that SSL trust cannot be established.

## Does this PR Introduce a Breaking Change?

[x] No

## Other Information

[AB#64704](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64704)

### CODE REVIEW

File: server.ts [hunk 1]
```diff
@@ -33,7 +35,6 @@ global['navigator'] = win.navigator;
 export function app() {
   const logging = /on|1|true|yes/.test(process.env.LOGGING?.toLowerCase());
 
-  const ICM_BASE_URL = process.env.ICM_BASE_URL || environment.icmBaseURL;
```
Comment (jometzner) [inline server.ts:36]: Moving this to a larger scope means that it lacks a "falsey" check at the right time. You are accessing this value in function `run()` but the falsey check is performed in `app` function. To late...

**Review by jometzner — CHANGES_REQUESTED** [review]

File: server.ts [hunk 2]
```diff
@@ -263,8 +264,53 @@ export function app() {
...
+      'CERT_REVOKED',
+      'INVALID_CA',
+      'INVALID_PURPOSE',
+      'CERT_UNTRUSTED',
+      'CERT_REJECTED',
+      'HOSTNAME_MISMATCH',
+    ];
+
+    req.on('error', e => {
+      if (certErrorCodes.indexOf(e.code) > -1) {
```
Comment (dhhyi) [inline server.ts:301]: [Array.includes](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

File: server.ts [hunk 3]
```diff
@@ -263,8 +264,53 @@ export function app() {
 }
 
 function run() {
+  const https = require('https');
```
Comment (dhhyi) [inline server.ts:267]: Shouldn't this check only be done if the ICM_BASE_URL actually starts with https? This check will always fail if I use a local URL without TLS

**Review by jometzner — APPROVED** [review]

**Review by jometzner — DISMISSED** [review]

**Review by jometzner — APPROVED** [review]
